### ISSUE TITLE
Check in `LensPops` catalog (or link to it)

### ISSUE THREAD

**Issue by drphilmarshall** [DES-SL/RingFinder2#11]
Hey @tcollett  - thinking about #6 but also more generally about interpreting BlueRings outputs, I think it would be helpful to provide access to the `LensPops` catalog from which the training set will be drawn, to drive algorithm development. This catalog can be reasonably assumed to be a fair sampling of the prior PDF for lens and source properties, which means we ought to be able to use it to help assess the plausibility of any Einstein radii we extract from the residual image analysis. I think we want the following columns, at least to start:

```
z_d    sigmaSIE_d    mag_g_d   mag_r_d   mag_i_d   mag_z_d   z_s   mag_g_s   mag_r_s   mag_i_s   mag_z_s   thetaE
```

What do you think? If the catalog you are using is small (<100k) you could check it in to a `data` folder in this repo. Otherwise, you could add a link to it from the README. Thanks!

**Comment by tcollett** [comment]
I didn't think we were going to use LensPop for the SW simulations. The
sims I'm using are SimCT from Anu. I've setup Colin with LensPop though.

**Comment by drphilmarshall** [comment]
OK, cool - the SimCT sims should have similar distributions. Do you have a
catalog like the one I am talking about, with predicted colors as well as
redshifts and masses? Anything would do to get started thinking about this
and #6

**Comment by tcollett** [comment]
Check out https://github.com/tcollett/LensPop/blob/master/lenses_DESa.txt

That's one example catalogue of discoverable lenses for DES coadds (full
area at 5 year depth though). There's plenty of stochasticity in the
catalogue though. I think Liz told me there's a bug in one of the columns
(but I can't remember what it is  - I think it's one of the discoverability
flags; all of those lenses are discoverable)

Cheers,
Tom

**Comment by drphilmarshall** [comment]
Great - that's almost exactly what we need. Do you have the z-band
magnitudes to match? The SED modeling in #6 would need this, I think.

**Comment by tcollett** [comment]
No I'm afraid not - I never simulated z band data. I could add it, but it
would take a complete rerun sadly.

Why not clone the repo and try yourself sometime!

**Comment by drphilmarshall** [comment]
I'll see if I can find time - and also to think more about how to use this
information. It'll be good to hear from James too, on what he can measure
from the residuals. We can close this out, then - thanks Tom.

**Comment by tcollett** [comment]
If you don't have the time I can do it (my comment about you doing it was
tongue-in-cheek) - I don't think there's a rush.

**Comment by drphilmarshall** [comment]
No, I agree - today I am mainly making sure everything is written down
after last week! I think completing a SW PNG production pipeline is
probably the first thing to get built: hopefully you, @bnord and James can
do this assembly while we think about enhancements in parallel.
